const DB_KEY="sdsPortalDB";const el=(id)=>document.getElementById(id);const getDB=()=>JSON.parse(localStorage.getItem(DB_KEY));const setDB=(d)=>localStorage.setItem(DB_KEY,JSON.stringify(d));
const seed={students:[],staff:[],notices:[{id:crypto.randomUUID(),type:"General Information",text:"सत्र 2026-27 प्रवेश प्रारम्भ",date:new Date().toLocaleDateString()}],meetings:[],branding:{}};if(!localStorage.getItem(DB_KEY))localStorage.setItem(DB_KEY,JSON.stringify(seed));
const toData=file=>new Promise(r=>{if(!file)return r("");const fr=new FileReader();fr.onload=e=>r(e.target.result);fr.readAsDataURL(file)});
const verifyOtp=(forWhat)=>{const otp=String(Math.floor(100000+Math.random()*900000));alert(`OTP for ${forWhat}: ${otp}`);const entered=prompt("Enter OTP / OTP दर्ज करें:");if(entered!==otp){alert("Invalid OTP / गलत OTP");return false;}return true;};
function metrics(){const d=getDB();el("metricStudents").textContent=d.students.length;el("metricStaff").textContent=d.staff.length;el("metricNotices").textContent=d.notices.length;el("metricMeetings").textContent=d.meetings.length;}
function renderStudents(){const d=getDB();el("studentTableBody").innerHTML=d.students.map(s=>`<tr><td>${s.fullName}</td><td>${s.studentClass}-${s.section}</td><td>${s.mobileNumber}</td><td><button class='btn btn-sm btn-warning' onclick="editStudent('${s.id}')">Edit</button> <button class='btn btn-sm btn-danger' onclick="delStudent('${s.id}')">Del</button></td></tr>`).join("");el("certificateStudent").innerHTML='<option value="">Select Student</option>'+d.students.map(s=>`<option value='${s.id}'>${s.fullName}</option>`).join('');metrics();}
function renderStaff(){const d=getDB();el("staffTableBody").innerHTML=d.staff.map(s=>`<tr><td>${s.name}</td><td>${s.designation}</td><td>${s.subject}</td><td><button class='btn btn-sm btn-warning' onclick="editStaff('${s.id}')">Edit</button> <button class='btn btn-sm btn-danger' onclick="delStaff('${s.id}')">Del</button></td></tr>`).join("");metrics();}
window.delStudent=id=>{const d=getDB();d.students=d.students.filter(s=>s.id!==id);setDB(d);renderStudents()};window.delStaff=id=>{const d=getDB();d.staff=d.staff.filter(s=>s.id!==id);setDB(d);renderStaff()};
window.editStudent=id=>{const s=getDB().students.find(x=>x.id===id);if(!s)return;el("studentId").value=s.id;["fullName","fatherName","motherName","studentClass","section","rollNumber","dob","studentAddress","mobileNumber","aadhaar"].forEach(k=>el(k).value=s[k]||"")};
window.editStaff=id=>{const s=getDB().staff.find(x=>x.id===id);if(!s)return;el("staffId").value=s.id;el("staffName").value=s.name;el("designation").value=s.designation;el("subject").value=s.subject;el("staffMobile").value=s.mobile};
el("adminLoginForm").addEventListener("submit",e=>{e.preventDefault();if(el("adminUsername").value==='admin'&&el("adminPassword").value==='sds123'){sessionStorage.setItem('sdsAdmin','1');showPanel()}else el("loginMessage").textContent='Wrong credentials / गलत जानकारी'});
function showPanel(){el("loginCard").hidden=true;el("adminPanel").hidden=false;renderStudents();renderStaff();}
if(sessionStorage.getItem('sdsAdmin')==='1')showPanel();
el("logoutBtn").addEventListener("click",()=>{sessionStorage.removeItem('sdsAdmin');location.reload()});
el("studentForm").addEventListener("submit",async e=>{e.preventDefault();if(!verifyOtp('Student Save'))return;const d=getDB();const id=el("studentId").value||crypto.randomUUID();const old=d.students.find(s=>s.id===id);const photo=el("studentPhoto").files[0]?await toData(el("studentPhoto").files[0]):(old?.photo||"");const s={id,photo,fullName:el("fullName").value,fatherName:el("fatherName").value,motherName:el("motherName").value,studentClass:el("studentClass").value,section:el("section").value,rollNumber:el("rollNumber").value,dob:el("dob").value,studentAddress:el("studentAddress").value,mobileNumber:el("mobileNumber").value,aadhaar:el("aadhaar").value};d.students=d.students.some(x=>x.id===id)?d.students.map(x=>x.id===id?s:x):[...d.students,s];setDB(d);e.target.reset();el("studentId").value='';renderStudents()});
el("staffForm").addEventListener("submit",async e=>{e.preventDefault();if(!verifyOtp('Staff Save'))return;const d=getDB();const id=el("staffId").value||crypto.randomUUID();const old=d.staff.find(s=>s.id===id);const photo=el("staffPhoto").files[0]?await toData(el("staffPhoto").files[0]):(old?.photo||"");const s={id,photo,name:el("staffName").value,designation:el("designation").value,subject:el("subject").value,mobile:el("staffMobile").value};d.staff=d.staff.some(x=>x.id===id)?d.staff.map(x=>x.id===id?s:x):[...d.staff,s];setDB(d);e.target.reset();el("staffId").value='';renderStaff()});
el("noticeForm").addEventListener("submit",e=>{e.preventDefault();const d=getDB();d.notices.unshift({id:crypto.randomUUID(),type:el("noticeType").value,text:el("noticeText").value,date:new Date().toLocaleDateString()});setDB(d);e.target.reset();metrics();alert('Notice added / सूचना जोड़ी गई')});
el("meetingForm").addEventListener("submit",e=>{e.preventDefault();const d=getDB();d.meetings.push({id:crypto.randomUUID(),date:el("meetingDate").value,time:el("meetingTime").value,purpose:el("meetingPurpose").value});setDB(d);e.target.reset();metrics();alert('Meeting added / बैठक जोड़ी गई')});
el("brandingForm").addEventListener("submit",async e=>{e.preventDefault();const d=getDB();d.branding={logo:el("logoInput").files[0]?await toData(el("logoInput").files[0]):d.branding.logo,banner:el("bannerInput").files[0]?await toData(el("bannerInput").files[0]):d.branding.banner,principal:el("principalInput").files[0]?await toData(el("principalInput").files[0]):d.branding.principal};setDB(d);alert('Branding saved / ब्रांडिंग सेव')});
el("certificateForm").addEventListener("submit",e=>{e.preventDefault();const d=getDB();const s=d.students.find(x=>x.id===el("certificateStudent").value);if(!s)return alert('Select student');const {jsPDF}=window.jspdf;const doc=new jsPDF();doc.text('S.D.S Convent School',105,20,{align:'center'});doc.text(el("certificateType").value,105,35,{align:'center'});doc.text(`Student: ${s.fullName}`,20,55);doc.text(`Class: ${s.studentClass}-${s.section}`,20,65);doc.text('Principal: Miss Joty Dewadi',20,90);doc.save(`${s.fullName}_certificate.pdf`)});
el("exportBackup").addEventListener("click",()=>{const b=new Blob([JSON.stringify(getDB(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='sds-backup.json';a.click()});
el("importBackup").addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;try{setDB(JSON.parse(await f.text()));renderStudents();renderStaff();alert('Backup imported')}catch{alert('Invalid file')}});
