CREATE DATABASE IF NOT EXISTS sds_school;
USE sds_school;

CREATE TABLE IF NOT EXISTS students (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_photo VARCHAR(255) NULL,
  full_name VARCHAR(120) NOT NULL,
  father_name VARCHAR(120) NOT NULL,
  mother_name VARCHAR(120) NOT NULL,
  class_name VARCHAR(20) NOT NULL,
  section VARCHAR(10) NOT NULL,
  roll_number VARCHAR(20) NOT NULL,
  dob DATE NOT NULL,
  address VARCHAR(255) NOT NULL,
  mobile VARCHAR(20) NOT NULL,
  aadhaar VARCHAR(20) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staff (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  designation VARCHAR(80) NOT NULL,
  subject VARCHAR(80) NOT NULL,
  mobile VARCHAR(20) NOT NULL,
  photo VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  notice_type VARCHAR(50) NOT NULL,
  notice_content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS meetings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  meeting_date DATE NOT NULL,
  meeting_time TIME NOT NULL,
  purpose VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contacts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
